<?php
/**
 * @Final File
 */
namespace app\modules\management\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\web\NotFoundHttpException;
use app\modules\management\models\SerialCode;
use kartik\mpdf\Pdf;

class SerialController extends Controller
{
    public $enableCsrfValidation = false;
    
    public $dataLayout = <<< HTML
    <div class="panel-heading">
        <div class="pull-left"><i class="fa fa-list"></i> {{list}}</div>
        <div class="pull-right">
            <a href="{{l_create}}" data-toggle="tooltip" title="{{t_create}}" class="btn btn-success btn-xs"><i class="fa fa-plus"></i></a>
        </div>
        <div class="clearfix"></div>
    </div>
    {items}
    <div class="panel-footer">
        <div class="pull-right">{summary}</div>
        <div class="pull-left">{pager}</div>
        <div class="clearfix"></div>
    </div>
HTML;
	public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only'  => ['index', 'create'],
                'rules' => [
                    [
                        'actions' => ['index', 'create', 'pdf-export'],
                        'allow'   => true,
                        'roles'   => ['Staff'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'index'      => ['get'],
                    'create'     => ['get', 'post'],
                    'pdf-export' => ['get'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
    	return $this->getList();
    }

    public function actionCreate()
    {
        if (Yii::$app->request->get('row')) {
            $model = new SerialCode;
            $data['model']  = $model->generateSerial(Yii::$app->request->get('row'));
            
            Yii::$app->session->set('model', $data);
            
            return $this->redirect(['/management/serial/pdf-export']);
        }

        $data['t_title'] = Yii::t('app', 'Serial Generator');
        Yii::$app->view->title = $data['t_title'];
        Yii::$app->view->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Management'), 'url' => ['/management']];
        Yii::$app->view->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Serial'), 'url' => ['/management/serial']];
        Yii::$app->view->params['breadcrumbs'][] = $data['t_title'];

        return $this->render('form', $data);
    }

    public function getList()
    {
        $model = new SerialCode;
        $data['model'] = $model;
        $data['dataProvider'] = $model->search(Yii::$app->request->queryParams);

        // Text
        $data['t_title']    = Yii::t('app', 'Serial');
        $data['t_create']   = Yii::t('app', 'Create');
        // Link
        $data['l_create']   = Url::to(['/management/serial/create']);

        $data['dataLayout'] = str_replace('{{list}}', Yii::t('app', 'List') . ' ' . $data['t_title'], $this->dataLayout);
        $data['dataLayout'] = str_replace('{{l_create}}', $data['l_create'], $data['dataLayout']);
        $data['dataLayout'] = str_replace('{{t_create}}', $data['t_create'], $data['dataLayout']);

        Yii::$app->view->title = $data['t_title'];
        Yii::$app->view->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Management'), 'url' => ['/management']];
        Yii::$app->view->params['breadcrumbs'][] = $data['t_title'];

        return $this->render('index', $data);
    }

    public function actionPdfExport()
    {
        $data = Yii::$app->session->get('model');

        $pdf = new Pdf([
            'mode' => Pdf::MODE_UTF8,
            'format' => Pdf::FORMAT_A4,
            //'destination' => Pdf::DEST_DOWNLOAD,
            'filename' => 'Serial-'.date('Y_m_d.His').'-'.rand(11111,999999).'.pdf',
            'content' => $this->renderPartial('generator', $data),
            'options' => [
                'title' => 'Serial Generator',
                'subject' => 'Generating Serial to PDF file'
            ],
            'methods' => [
                'SetHeader' => ['Generated By: KDSSTSC||Generated On: ' . date("r")],
                'SetFooter' => ['|Page {PAGENO}|'],
            ]
        ]);

        return $pdf->render();
    }
}
